### ISSUE TITLE
flutter: Error: NoSuchMethodError: The method 'signUp' was called on null.

### ISSUE THREAD

**Issue by xiangxinyue** [IndustryBear/Aspire#79]
**Describe the bug**
flutter: Error: NoSuchMethodError: The method 'signUp' was called on null.
Receiver: null
Tried calling: signUp("xxiang2@ualberta.ca", "123456")
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: Class 'NoSuchMethodError' has no instance getter 'message'.
Receiver: Instance of 'NoSuchMethodError'
Tried calling: message
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _LoginSignupPageState.validateAndSubmit.<anonymous closure> (package:aspire/ftu/signup.dart:66:29)
#2      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
#3      _LoginSignupPageState.validateAndSubmit (package:aspire/ftu/signup.dart:64:9)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
#9      BaseTa<…>

**Expected behavior**
The email and password should send to firebase for signup.

**Screenshots**
<img width="1792" alt="Screen Shot 2020-06-18 at 9 46 34 AM" src="https://user-images.githubusercontent.com/44979399/85043219-57ae6f80-b149-11ea-82c7-220f89f2f201.png">

**Smartphone (please complete the following information):**
 - Device: Pad Pro (12.9-inch) (4th generation)

**Comment by xiangxinyue** [comment]
Add a root page for init the auth can solve this issue
